In [214]:
import pickle
import os
import numpy as np
from sklearn.metrics import balanced_accuracy_score

In [215]:
def load_pkl_dictionary(filepath):
    saved_dictionary_test = None
    with open(filepath,'rb') as f:
        saved_dictionary_test = pickle.load(f)
    return saved_dictionary_test

In [216]:
def to_percent(n, decimals=2):
    return np.round(n*100, decimals)

In [217]:
def report_mae(results):
    LFLSTMP_average_mae = [results[key][2][2] for key in results.keys() if key[0] == "LFLSTMP"]
    LFLSTM_average_mae = [results[key][2][2] for key in results.keys() if key[0] == "LFLSTM"]
    EFLSTMP_average_mae = [results[key][2][2] for key in results.keys() if key[0] == "EFLSTMP"]
    EFLSTM_average_mae = [results[key][2][2] for key in results.keys() if key[0] == "EFLSTM"]
    print("MAE:")
    print("LFLSTM w/ Pose: ", np.round(np.array(LFLSTMP_average_mae).mean(),3))
    print("LFLSTM NO Pose: ", np.round(np.array(LFLSTM_average_mae).mean(),3))
    print("EFLSTM w/ Pose: ", np.round(np.array(EFLSTMP_average_mae).mean(),3))
    print("EFLSTM NO Pose: ", np.round(np.array(EFLSTM_average_mae).mean(),3))
    return LFLSTMP_average_mae, LFLSTM_average_mae, EFLSTMP_average_mae, EFLSTM_average_mae
    

In [242]:
def report_f1_acc(results):
    LFLSTMP_average_acc = [balanced_accuracy_score(results[key][2][1], results[key][2][0]) for key in results.keys() if key[0] == "LFLSTMP"]
    LFLSTM_average_acc = [balanced_accuracy_score(results[key][2][1], results[key][2][0])  for key in results.keys() if key[0] == "LFLSTM"]
    EFLSTM_average_acc = [balanced_accuracy_score(results[key][2][1], results[key][2][0])  for key in results.keys() if key[0] == "EFLSTMP"]
    EFLSTMNP_average_acc = [balanced_accuracy_score(results[key][2][1], results[key][2][0])  for key in results.keys() if key[0] == "EFLSTM"]
    LFLSTMP_average_f1 = [results[key][2][2][0] for key in results.keys() if key[0] == "LFLSTMP"]
    LFLSTM_average_f1 = [results[key][2][2][0] for key in results.keys() if key[0] == "LFLSTM"]
    EFLSTM_average_f1 = [results[key][2][2][0] for key in results.keys() if key[0] == "EFLSTMP"]
    EFLSTMNP_average_f1 = [results[key][2][2][0] for key in results.keys() if key[0] == "EFLSTM"]

    print("Weighted Acc:")
    print("LFLSTMP: ", to_percent(np.array(LFLSTMP_average_acc).mean()))
    print("LFLSTM: ",  to_percent(np.array(LFLSTM_average_acc).mean()))
    print("EFLSTMP: ", to_percent(np.array(EFLSTMNP_average_acc).mean()))
    print("EFLSTM: ",  to_percent(np.array(EFLSTM_average_acc).mean()))
    print("Average F1:")
    print("LFLSTMP: ", to_percent(np.array(LFLSTMP_average_f1).mean()))
    print("LFLSTM: ",  to_percent(np.array(LFLSTM_average_f1).mean()))
    print("EFLSTMP: ", to_percent(np.array(EFLSTMNP_average_f1).mean()))
    print("EFLSTM: ",  to_percent(np.array(EFLSTM_average_f1).mean()))
    return  ((LFLSTMP_average_acc, LFLSTMP_average_f1), (LFLSTM_average_acc,LFLSTM_average_f1),
        (EFLSTM_average_acc, EFLSTM_average_f1), (EFLSTMNP_average_acc, EFLSTMNP_average_f1))
    

In [219]:
def get_all_labels(valued_dict):
    test_videos = set()
    labels_dict = dict()
    for k,v in valued_dict.items():
        if k == "videos":
            continue
        classifier, t, d = k
        if t not in test_videos:
            test_videos.add(t)
            labels_dict[t] = valued_dict[k][2][1]
    return labels_dict

In [220]:
sentiment_mae = load_pkl_dictionary("results_dictionary_top10_mae.pkl")

In [221]:
results_mae = report_mae(sentiment_mae)

MAE:
LFLSTM w/ Pose:  1.693
LFLSTM NO Pose:  1.701
EFLSTM w/ Pose:  1.653
EFLSTM NO Pose:  1.647


In [222]:
sentiment_2c = load_pkl_dictionary("results_dictionary_top10_s2c.pkl")

In [223]:
results_sentiment_2c = report_f1_acc_s2c(sentiment_2c)

Average Acc:
LFLSTMP:  54.11
LFLSTM:  46.31
EFLSTMP:  51.4
EFLSTM:  44.29
Average F1:
LFLSTMP:  57.08
LFLSTM:  50.59
EFLSTMP:  58.24
EFLSTM:  51.2


In [224]:
sentiment_7c = load_pkl_dictionary("results_dictionary_top10_s7c.pkl")

In [225]:
results_sentiment_7c = report_f1_acc(sentiment_7c)

Weighted Acc:
LFLSTMP:  14.63
LFLSTM:  10.12
EFLSTMP:  13.46
EFLSTM:  12.61
Average F1:
LFLSTMP:  14.08
LFLSTM:  9.56
EFLSTMP:  14.3
EFLSTM:  13.7


C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains

In [241]:
get_all_labels(sentiment_7c)

{0: array([1, 2, 1, 0, 3], dtype=int64),
 1: array([5, 5, 5], dtype=int64),
 2: array([6, 5, 4, 5, 5, 5, 5, 5], dtype=int64),
 3: array([3], dtype=int64),
 4: array([1, 1, 2, 2], dtype=int64),
 5: array([6, 5], dtype=int64),
 6: array([2, 1], dtype=int64),
 7: array([5, 6], dtype=int64),
 8: array([3, 2, 3], dtype=int64),
 9: array([0, 1, 0, 1, 2], dtype=int64)}

In [226]:
happy_4c = load_pkl_dictionary("results_dictionary_top10_h4c.pkl")
sad_4c = load_pkl_dictionary("results_dictionary_top10_s4c.pkl")
anger_4c = load_pkl_dictionary("results_dictionary_top10_a4c.pkl")
fear_4c = load_pkl_dictionary("results_dictionary_top10_f4c.pkl")
disgust_4c = load_pkl_dictionary("results_dictionary_top10_d4c.pkl")
surprise_4c = load_pkl_dictionary("results_dictionary_top10_surprise4c.pkl")

In [243]:
vals_happy_4c = report_f1_acc(happy_4c)

Weighted Acc:
LFLSTMP:  33.12
LFLSTM:  26.04
EFLSTMP:  26.7
EFLSTM:  20.04
Average F1:
LFLSTMP:  38.28
LFLSTM:  31.49
EFLSTMP:  33.29
EFLSTM:  24.42


C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains

In [246]:
vals_happy_4c[0][0]

[(array([0, 0, 0, 0, 1], dtype=int64), array([1, 0, 0, 0, 0], dtype=int64)),
 (array([0, 0, 0, 0, 1], dtype=int64), array([0, 0, 0, 0, 0], dtype=int64)),
 (array([0, 0, 0, 0, 1], dtype=int64), array([1, 1, 2, 0, 1], dtype=int64)),
 (array([0, 0, 0, 0, 1], dtype=int64), array([3, 1, 3, 3, 3], dtype=int64)),
 (array([0, 0, 0, 0, 1], dtype=int64), array([1, 0, 0, 1, 1], dtype=int64)),
 (array([0, 0, 0, 0, 1], dtype=int64), array([0, 0, 0, 0, 0], dtype=int64)),
 (array([0, 0, 0, 0, 1], dtype=int64), array([2, 1, 1, 1, 1], dtype=int64)),
 (array([0, 0, 0, 0, 1], dtype=int64), array([3, 1, 3, 3, 3], dtype=int64)),
 (array([0, 0, 0, 0, 1], dtype=int64), array([2, 2, 0, 2, 2], dtype=int64)),
 (array([2, 2, 2], dtype=int64), array([0, 2, 0], dtype=int64)),
 (array([2, 2, 2], dtype=int64), array([0, 2, 0], dtype=int64)),
 (array([2, 2, 2], dtype=int64), array([0, 0, 0], dtype=int64)),
 (array([2, 2, 2], dtype=int64), array([0, 2, 0], dtype=int64)),
 (array([2, 2, 2], dtype=int64), array([0, 2, 3

In [247]:
vals_happy_4c[0][1]

[(array([0, 0, 0, 0, 1], dtype=int64), array([3, 3, 3, 1, 3], dtype=int64)),
 (array([0, 0, 0, 0, 1], dtype=int64), array([2, 2, 2, 2, 2], dtype=int64)),
 (array([0, 0, 0, 0, 1], dtype=int64), array([1, 1, 2, 1, 0], dtype=int64)),
 (array([0, 0, 0, 0, 1], dtype=int64), array([0, 0, 0, 0, 0], dtype=int64)),
 (array([0, 0, 0, 0, 1], dtype=int64), array([0, 0, 0, 0, 0], dtype=int64)),
 (array([0, 0, 0, 0, 1], dtype=int64), array([0, 0, 2, 0, 0], dtype=int64)),
 (array([0, 0, 0, 0, 1], dtype=int64), array([0, 0, 1, 0, 0], dtype=int64)),
 (array([0, 0, 0, 0, 1], dtype=int64), array([3, 0, 3, 0, 3], dtype=int64)),
 (array([0, 0, 0, 0, 1], dtype=int64), array([0, 0, 0, 0, 3], dtype=int64)),
 (array([2, 2, 2], dtype=int64), array([0, 2, 0], dtype=int64)),
 (array([2, 2, 2], dtype=int64), array([2, 1, 2], dtype=int64)),
 (array([2, 2, 2], dtype=int64), array([2, 0, 0], dtype=int64)),
 (array([2, 2, 2], dtype=int64), array([0, 2, 2], dtype=int64)),
 (array([2, 2, 2], dtype=int64), array([0, 0, 0

In [228]:
get_all_labels(happy_4c)

{0: array([0, 0, 0, 0, 1], dtype=int64),
 1: array([2, 2, 2], dtype=int64),
 2: array([3, 2, 2, 2, 2, 2, 2, 3], dtype=int64),
 3: array([0], dtype=int64),
 4: array([0, 0, 0, 0], dtype=int64),
 5: array([2, 2], dtype=int64),
 6: array([0, 0], dtype=int64),
 7: array([1, 1], dtype=int64),
 8: array([2, 0, 0], dtype=int64),
 9: array([0, 0, 0, 0, 0], dtype=int64)}

In [229]:
vals_sad_4c = report_f1_acc(sad_4c)

Weighted Acc:
LFLSTMP:  79.56
LFLSTM:  83.51
EFLSTMP:  75.4
EFLSTM:  77.56
Average F1:
LFLSTMP:  79.01
LFLSTM:  82.65
EFLSTMP:  74.36
EFLSTM:  77.87


C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains

In [239]:
sad_4c['videos']

['Va54WZgPTdY',
 '1LkYxsqRPZM',
 'tkzdanzsA0A',
 'OwYfPi9St0w',
 'o2bNnLOEEC0',
 'rWjPSlzUc-8',
 'pVs1daijYTw',
 'N-NnCI6U52c',
 '-tANM6ETl_M',
 'XQOUZhWI1B0']

In [230]:
get_all_labels(sad_4c)

{0: array([0, 0, 0, 0, 0], dtype=int64),
 1: array([0, 0, 0], dtype=int64),
 2: array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 3: array([0], dtype=int64),
 4: array([1, 2, 2, 0], dtype=int64),
 5: array([0, 0], dtype=int64),
 6: array([0, 0], dtype=int64),
 7: array([0, 0], dtype=int64),
 8: array([0, 0, 0], dtype=int64),
 9: array([0, 0, 0, 0, 0], dtype=int64)}

In [231]:
vals_anger_4c = report_f1_acc(anger_4c)

Weighted Acc:
LFLSTMP:  28.61
LFLSTM:  29.03
EFLSTMP:  35.93
EFLSTM:  28.56
Average F1:
LFLSTMP:  30.03
LFLSTM:  29.48
EFLSTMP:  37.13
EFLSTM:  30.04


C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains

In [232]:
get_all_labels(anger_4c)

{0: array([1, 2, 1, 2, 0], dtype=int64),
 1: array([0, 0, 0], dtype=int64),
 2: array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 3: array([0], dtype=int64),
 4: array([2, 0, 0, 2], dtype=int64),
 5: array([0, 0], dtype=int64),
 6: array([0, 2], dtype=int64),
 7: array([0, 0], dtype=int64),
 8: array([0, 0, 0], dtype=int64),
 9: array([2, 1, 3, 2, 1], dtype=int64)}

In [233]:
vals_fear_4c = report_f1_acc(fear_4c)

Weighted Acc:
LFLSTMP:  84.19
LFLSTM:  85.8
EFLSTMP:  74.15
EFLSTM:  70.34
Average F1:
LFLSTMP:  85.15
LFLSTM:  86.17
EFLSTMP:  74.52
EFLSTM:  71.91


C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains

In [234]:
get_all_labels(fear_4c)

{0: array([0, 0, 0, 0, 0], dtype=int64),
 1: array([0, 0, 0], dtype=int64),
 2: array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 3: array([0], dtype=int64),
 4: array([0, 0, 1, 0], dtype=int64),
 5: array([0, 0], dtype=int64),
 6: array([0, 0], dtype=int64),
 7: array([1, 0], dtype=int64),
 8: array([0, 0, 0], dtype=int64),
 9: array([0, 0, 0, 0, 0], dtype=int64)}

In [235]:
vals_disgust_4c = report_f1_acc(disgust_4c)

Weighted Acc:
LFLSTMP:  52.07
LFLSTM:  52.87
EFLSTMP:  53.77
EFLSTM:  52.09
Average F1:
LFLSTMP:  54.61
LFLSTM:  54.09
EFLSTMP:  54.34
EFLSTM:  52.95


C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains

In [236]:
get_all_labels(disgust_4c)

{0: array([0, 0, 0, 0, 0], dtype=int64),
 1: array([0, 0, 0], dtype=int64),
 2: array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 3: array([0], dtype=int64),
 4: array([1, 0, 0, 1], dtype=int64),
 5: array([0, 0], dtype=int64),
 6: array([0, 0], dtype=int64),
 7: array([0, 0], dtype=int64),
 8: array([0, 1, 0], dtype=int64),
 9: array([1, 0, 2, 1, 0], dtype=int64)}

In [237]:
vals_surprise_4c = report_f1_acc(surprise_4c)

Weighted Acc:
LFLSTMP:  100.0
LFLSTM:  100.0
EFLSTMP:  96.15
EFLSTM:  91.07
Average F1:
LFLSTMP:  100.0
LFLSTM:  100.0
EFLSTMP:  96.48
EFLSTM:  92.01


C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
C:\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains

In [238]:
get_all_labels(surprise_4c)

{0: array([0, 0, 0, 0, 0], dtype=int64),
 1: array([0, 0, 0], dtype=int64),
 2: array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 3: array([0], dtype=int64),
 4: array([0, 0, 0, 0], dtype=int64),
 5: array([0, 0], dtype=int64),
 6: array([0, 0], dtype=int64),
 7: array([0, 0], dtype=int64),
 8: array([0, 0, 0], dtype=int64),
 9: array([0, 0, 0, 0, 0], dtype=int64)}